### ISSUE TITLE
PERF: add `loc` parameter to the `plot_series` function

### ISSUE THREAD

**Issue by axelfahy** [axelfahy/bff#24]
Default location for `loc` in legend is `best`, which raise the following warning when used with lots of data: `UserWarning: Creating legend with loc="best" can be slow with large amounts of data.`

Add the possibility to specify the location of the legend with the parameters function.

**Comment by sullyfischer** [comment]
May I ask how you got to silent the warning?

**Comment by axelfahy** [comment]
I did not silent the warning, instead I added the ``loc`` option to specify a more precise location than ``best``. The ``best`` location is much slower, because it needs to find a location. If you specify a location, for example ``loc='upper left'``, this will be faster and the warnings won't be raised.

However, you could probably silence the warning using something similar to this: 
```
import warnings
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    ax.plot(..., loc='best')
```
